### ISSUE TITLE
Valgrind error with "sga assemble": Conditional jump or move depends on uninitialised value(s)

### ISSUE THREAD

**Issue by NG0S** [jts/sga#100]
While running the whole sga pipeline on a small fastq file, I observed an error with valgrind during the "sga assemble" step.

valgrind /home/localspace/pericard/programmes/sga/src/SGA/sga assemble -m 30 -g 0 -r 10 -d 0.03 -g 0.03 -o assemble.m30 merged.k21.rmdup.asqg.gz
==12298== Memcheck, a memory error detector
==12298== Copyright (C) 2002-2011, and GNU GPL'd, by Julian Seward et al.
==12298== Using Valgrind-3.7.0 and LibVEX; rerun with -h for copyright info
==12298== Command: /home/localspace/pericard/programmes/sga/src/SGA/sga assemble -m 30 -g 0 -r 10 -d 0.03 -g 0.03 -o assemble.m30 merged.k21.rmdup.asqg.gz
==12298== 
==12298== Conditional jump or move depends on uninitialised value(s)
==12298==    at 0x524786: SGSuperRepeatVisitor::visit(Bigraph*, Vertex*) (in /home/localspace/pericard/programmes/sga/src/SGA/sga)
==12298==    by 0x51EE37: bool Bigraph::visit<SGSuperRepeatVisitor>(SGSuperRepeatVisitor&) (in /home/localspace/pericard/programmes/sga/src/SGA/sga)
==12298==    by 0x51E526: SGUtil::loadASQG(std::string const&, unsigned int, bool, unsigned long) (in /home/localspace/pericard/programmes/sga/src/SGA/sga)
==12298==    by 0x417042: assemble() (in /home/localspace/pericard/programmes/sga/src/SGA/sga)
==12298==    by 0x4185DF: assembleMain(int, char**) (in /home/localspace/pericard/programmes/sga/src/SGA/sga)
==12298==    by 0x40B2BA: main (in /home/localspace/pericard/programmes/sga/src/SGA/sga)
==12298== 

I attached the bash file i'm running, a small fastq file test, and the log file i'm obtaining.
[SRA_LTP.test_dataset.rrna.sample.fastq.txt](https://github.com/jts/sga/files/62786/SRA_LTP.test_dataset.rrna.sample.fastq.txt)
[test_assembly.sga.log.txt](https://github.com/jts/sga/files/62788/test_assembly.sga.log.txt)
[test_assembly.sh.txt](https://github.com/jts/sga/files/62787/test_assembly.sh.txt)

**Comment by jts** [comment]
Thanks for the report, this is fixed in 7eae8ab37
