### ISSUE TITLE
configure not working

### ISSUE THREAD

**Issue by Sameth** [jts/sga#114]
Running ./configure with appropriate paths to bamtools and sparsehash yields the following:

checking google/sparse_hash_set usability... no
checking google/sparse_hash_set presence... yes
configure: WARNING: google/sparse_hash_set: present but cannot be compiled
configure: WARNING: google/sparse_hash_set:     check for missing prerequisite headers?
configure: WARNING: google/sparse_hash_set: see the Autoconf documentation
configure: WARNING: google/sparse_hash_set:     section "Present But Cannot Be Compiled"
configure: WARNING: google/sparse_hash_set: proceeding with the compiler's result
configure: WARNING:     ## -------------------------------- ##
configure: WARNING:     ## Report this to js18@sanger.ac.uk ##
configure: WARNING:     ## -------------------------------- ##
checking for google/sparse_hash_set... no
configure: error: google sparse hash library is required: http://code.google.com/p/google-sparsehash/

**Comment by jts** [comment]
Hi,

Can you let me know what version of sparsehash you used, and the version of gcc?

Thanks,
Jared

**Comment by Sameth** [comment]
Hello,

I've already found a work-around, but first things first.

Gcc version: 4.9.2 (Ubuntu 4.9.2-10ubuntu13)
Sparsehash: used the last version from repo (i. e. this commit: https://github.com/sparsehash/sparsehash/commit/4a36398d442cc86f47d2d7e751596cc2430ad135 ).

I have -std=c++11 in my CXXFLAGS, but even changing that to c++03 didn't help. What did help was reinstalling sparsehash with c++03 (duh).

Thanks for your interest,
Jaroslav Petrucha

**Comment by jts** [comment]
Thanks for reporting back, sorry it took me so long to reply. It sounds like this issue is resolved so I'll close it.

**Comment by weijianwen** [comment]
Similar errors arise when building SGA with GCC 6. Rebuiling SGA with GCC 5.4 and sparsehash 2.0.3 (without modifying flags) solves this issues.

**Comment by odoublewen** [comment]
I would love to figure out how to get sga to compile with modern versions of gcc.

I have a tree of tools that I compile with gcc 8.2.0 , but I run into the same issue reported here.  I'll try to figure it out and report back anything I learn.... if anyone else has suggestions, I'd also appreciate them!

**Comment by numpde** [comment]
Same problem with
gcc (Ubuntu 9.3.0-10ubuntu2) 9.3.0

sparsehash 2.0.3-1 installed with
sudo apt install libsparsehash-dev

**Comment by Rohit-Satyam** [comment]
Did anyone got success in resolving this problem??
