### ISSUE TITLE
pre-process 

### ISSUE THREAD

**Issue by hermeseduardo** [jts/sga#127]
Hi, should we do quality trimming before using sga preqc, assembly with sga? In my case I have Illumina paired end data.
Any chance to allow hybrid assembly (Illumina+PacBio) data in the future?
thanks

**Comment by jts** [comment]
I suggest you don't quality trim before using preqc. After looking at the preqc report you can decide whether to trim or not (I typically do not suggest to trim unless the error rate at the ends of the reads is extremely high).

It is very unlikely that I will extend SGA to allow hybrid assembly, sorry.

**Comment by hermeseduardo** [comment]
OK thanks!!

2016-08-29 18:48 GMT+02:00 Jared Simpson <notifications@github.com>:
