### ISSUE TITLE
Blank sections in preqc results

### ISSUE THREAD

**Issue by genes-and-genomes** [jts/sga#140]
Some datasets produce blank graphs for:
variant branches in k-de Bruijn graph
repeat branches in k-de Bruijn graph
error branches in k-de Bruijn graph

Looking into the preqc files for these datasets that produce blank graphs, 'BranchClassification' is blank. See below for a normal preqc file and one with blank 'BranchClassification'.
![image](https://user-images.githubusercontent.com/9111098/28786110-3919b77e-75e6-11e7-9a88-2da66f1e7d8f.png)
![image](https://user-images.githubusercontent.com/9111098/28786133-45b60280-75e6-11e7-80a3-88ec26f62a5b.png)

I have not been able to identify a pattern for why some datasets produce all the graphs while some don't. I am running SGA 0.10.15.

**Comment by jts** [comment]
Hi,

If the sequencing depth is too low then the branch classifications may be inaccurate. When this situation is detected there will be no branch classifications output.

Jared
