### ISSUE TITLE
celegans.pe file not found 

### ISSUE THREAD

**Issue by pursue9190** [jts/sga#151]
When I run
  sga-align --name celegans.pe assemble.m75-contigs.fa s_6_1.fastq.gz  s_6_2.fastq.gz

Who can help me ?
Thanks

**Comment by jts** [comment]
Can you send the full error message?

Jared

**Comment by pursue9190** [comment]
:~/tvelvet$ /home/ubuntu/sga_master/src/bin/sga-align --name celegans.pe assemble.m75-contigs.fa s_6_1.fastq.gz  s_6_2.fastq.gz
assemble.m75-contigs.fa
['s_6_1.fastq.gz', 's_6_2.fastq.gz']

________________________________________
Tasks which will be run:


Task enters queue = 'indexContigs' 
bwa index assemble.m75-contigs.fa
/bin/sh: 1: bwa: not found
Completed Task = 'indexContigs' 
Task enters queue = 'prepareReads' 
Completed Task = 'prepareReads' 
Task enters queue = 'alignReads' 
bwa aln -o 0 -t 1 assemble.m75-contigs.fa s_6_1.fastq.gz > s_6_1.fastq.assemble.m75-contigs.bwsai
/bin/sh: 1: bwa: not found
bwa aln -o 0 -t 1 assemble.m75-contigs.fa s_6_2.fastq.gz > s_6_2.fastq.assemble.m75-contigs.bwsai
/bin/sh: 1: bwa: not found
bwa sampe -s assemble.m75-contigs.fa s_6_1.fastq.assemble.m75-contigs.bwsai s_6_2.fastq.assemble.m75-contigs.bwsai s_6_1.fastq.gz s_6_2.fastq.gz | samtools view -Sb -o celegans.pe.bam -
/bin/sh: 1: bwa: not found
/bin/sh: 1: samtools: not found
Completed Task = 'alignReads' 
Task enters queue = 'sortBAM' 
Traceback (most recent call last):
  File "/home/ubuntu/sga_master/src/bin/sga-align", line 162, in <module>
    pipeline_run([sortBAM])
  File "/usr/local/lib/python2.7/dist-packages/ruffus/task.py", line 5916, in pipeline_run
    raise job_errors
ruffus.ruffus_exceptions.RethrownJobError: 
    
    
    
Original exception:

    Exception #1
      '<class 'ruffus.ruffus_exceptions.RethrownJobError'>
        
        Exceptions generating parameters for
        
        task = 'sortBAM'
        
    Original exception:
    
        Exception #1
          'ruffus.ruffus_exceptions.MissingInputFileError(    
            
            
            No way to run job: Input file 'celegans.pe.bam' does not exist)' raised in ...
           Task = def sortBAM(...):
           
        
        Traceback (most recent call last):
          File "/usr/local/lib/python2.7/dist-packages/ruffus/task.py", line 5118, in parameter_generator
            job_history, verbose_abbreviated_path):
          File "/usr/local/lib/python2.7/dist-packages/ruffus/task.py", line 4945, in job_needs_to_run
            check_input_files_exist(*params)
          File "/usr/local/lib/python2.7/dist-packages/ruffus/file_name_parameters.py", line 399, in check_input_files_exist
            "Input file '%s' does not exist" % f)
        MissingInputFileError:     
            
            
            No way to run job: Input file 'celegans.pe.bam' does not exist
        
        ' raised in ...
    Traceback (most recent call last):
      File "/usr/local/lib/python2.7/dist-packages/ruffus/task.py", line 5887, in pipeline_run
        verbose)
      File "/usr/local/lib/python2.7/dist-packages/ruffus/task.py", line 5283, in fill_queue_with_job_parameters
        for params in job_parameters:
      File "/usr/local/lib/python2.7/dist-packages/ruffus/task.py", line 5215, in parameter_generator
        raise errt
    RethrownJobError: 
        
        Exceptions generating parameters for
        
        task = 'sortBAM'
        
    Original exception:
    
        Exception #1
          'ruffus.ruffus_exceptions.MissingInputFileError(    
            
            
            No way to run job: Input file 'celegans.pe.bam' does not exist)' raised in ...
           Task = def sortBAM(...):
           
        
        Traceback (most recent call last):
          File "/usr/local/lib/python2.7/dist-packages/ruffus/task.py", line 5118, in parameter_generator
            job_history, verbose_abbreviated_path):
          File "/usr/local/lib/python2.7/dist-packages/ruffus/task.py", line 4945, in job_needs_to_run
            check_input_files_exist(*params)
          File "/usr/local/lib/python2.7/dist-packages/ruffus/file_name_parameters.py", line 399, in check_input_files_exist
            "Input file '%s' does not exist" % f)
        MissingInputFileError:     
            
            
            No way to run job: Input file 'celegans.pe.bam' does not exist

**Comment by pursue9190** [comment]
Thanks for your help,I solved this problem.

**Comment by pursue9190** [comment]
What about this?

leted Task = 'sortBAM' 
+ /home/ubuntu/sga_master/src/bin/sga-bam2de.pl -n 5 --prefix libPE celegans.pe.bam
abyss-fixmate -h libPE.tmp.hist celegans.pe.bam | samtools view -Sb - > libPE.diffcontigs.bam
[samopen] SAM header is present: 3193 sequences.
Mateless          0
Unaligned    288422  2.03%
Singleton   2046151  14.4%
FR         11595602  81.6%
RF                3  2.11e-05%
FF                3  2.11e-05%
Different    284143  2%
Total      14214324
awk '$2 >= 3' libPE.tmp.hist > libPE.hist
samtools sort -@1 -o libPE.diffcontigs.sorted.bam libPE.diffcontigs.bam
open: No such file or directory
[bam_sort_core] fail to open file libPE.diffcontigs.sorted.bam
DistanceEst -s 200 --mind -99 -n 5 -k 99 -j 1 -o libPE.de libPE.hist -l 30 libPE.diffcontigs.sorted.bam
error: `libPE.diffcontigs.sorted.bam': No such file or directory
+ /home/ubuntu/sga_master/src/bin/sga-astat.py -m 200 celegans.pe.refsort.bam
Reading alignments from celegans.pe.refsort.bam
[E::hts_open_format] Failed to open file celegans.pe.refsort.bam
Traceback (most recent call last):
  File "/home/ubuntu/sga_master/src/bin/sga-astat.py", line 76, in <module>
    bamFile = pysam.Samfile(bamFilename, "rb")
  File "pysam/libcalignmentfile.pyx", line 729, in pysam.libcalignmentfile.AlignmentFile.__cinit__
  File "pysam/libcalignmentfile.pyx", line 919, in pysam.libcalignmentfile.AlignmentFile._open
IOError: [Errno 2] could not open alignment file `celegans.pe.refsort.bam`: No such file or directory
+ sga scaffold -m 200 --pe libPE.de -a libPE.astat -o scaffolds.n5.scaf assemble.m75-contigs.fa
Reading distance estimates from libPE.de
Error: could not open libPE.de for read
+ sga scaffold2fasta -m 200 -a assemble.m75-graph.asqg.gz -o scaffolds.n5.fa -d 1 --use-overlap --write-unplaced scaffolds.n5.scaf
Graph best: 0
Graph unique: 1
Find overlaps: 4
Deleted edges for 0 super repetitive vertices
Warning: removed 4 duplicate edges
Vertices: 3193 Edges: 8884 Islands: 21 Tips: 102 Monobranch: 1420 Dibranch: 510 Simple: 2610
Num scaffolds: 0
Num gaps attempted: 0
Num gaps resolved: 0
Num gaps resolved by graph walk: 0
Num graph walks failed because of too many solutions: 0
Num graph walks failed because of no path: 0
Num gaps resolved by overlap: 0
Num overlaps failed: 0

**Comment by pursue9190** [comment]
/home/ubuntu/sga_master/src/bin/sga-bam2de.pl -n 5 --prefix libPE celegans.pe.bam
abyss-fixmate -h libPE.tmp.hist celegans.pe.bam | samtools view -Sb - > libPE.diffcontigs.bam
[samopen] SAM header is present: 3193 sequences.
Mateless 0
Unaligned 288422 2.03%
Singleton 2046151 14.4%
FR 11595602 81.6%
RF 3 2.11e-05%
FF 3 2.11e-05%
Different 284143 2%
Total 14214324
awk '$2 >= 3' libPE.tmp.hist > libPE.hist
samtools sort -@1 -o libPE.diffcontigs.sorted.bam libPE.diffcontigs.bam
open: No such file or directory

**Comment by jts** [comment]
what version of `samtools` are you using?

**Comment by pursue9190** [comment]
samtools is already the newest version (0.1.19-1ubuntu1).

**Comment by pursue9190** [comment]
version (0.1.19-1ubuntu1).

**Comment by jts** [comment]
That is a very old version, the newest is 1.8:

https://github.com/samtools/samtools/releases/tag/1.8

Can you try 1.8?

**Comment by pursue9190** [comment]
Thank you  very much ,I tried it and the problem was solved.

**Comment by jts** [comment]
Great, glad it is working.
