### ISSUE TITLE
error while loading shared libraries: libbamtools.so.2.5.1

### ISSUE THREAD

**Issue by benliu5085** [jts/sga#154]
Hi
I have install bamtools and sparsehash and compiled sga, but when I tried to run sga, by calling sga, it gives me the error message:
sga: error while loading shared libraries: libbamtools.so.2.5.1: cannot open shared object file: No such file or directory

I am not sure why it keeps asking for libbamtools.so.2.5.1, because I tried:

1) install the newest bamtools, updated on Nov 12, 2018, but it gives me the same error message 
2) install an older version of bamtools, libbamtools.so.2.4.1, but the problem is still here.

Would you please help me resolve this?

Thanks
Ben

**Comment by jts** [comment]
Can you attach the complete log of when you ran `configure` and `make`?

**Comment by benliu5085** [comment]
> Can you attach the complete log of when you ran `configure` and `make`?

Hi Jared

I identified the problem, I called it wrong. 
it should run by:
    ./sga. 
But I called it as:
    sga

Thanks for the quick reply.

Sincerely
Ben
