### ISSUE TITLE
Compile error on 32-bit Ubuntu

### ISSUE THREAD

**Issue by LeeMendelowitz** [jts/sga#28]
When compiling on a 32-bit system, I received this compilation error:

LRAlignment.cpp: In function ‘void LRAlignment::removeDuplicateCells(LRAlignment::LRStackEntry*, LRAlignment::LRHash&)’:
LRAlignment.cpp:560:37: error: left shift count >= width of type [-Werror]
LRAlignment.cpp:566:30: error: left shift count >= width of type [-Werror]
cc1plus: all warnings being treated as errors

**Comment by tillea** [comment]
Since there are now official Debian packages I guess this old issue can be closed.
