### ISSUE TITLE
Describe the ASQG file format

### ISSUE THREAD

**Issue by sjackman** [jts/sga#66]
Here's a relevant [posting](https://groups.google.com/forum/#!msg/sga-users/rInkDEUof-I/n5tKTEqPXEUJ).

**Comment by Vini2** [comment]
What is the idea behind a number of differences in overlap value for -1? For example, I have the following output and would like to know the correct interpretation.

`ED	contig-1510 contig-1658 0 289 1269 38 327 328 0 -1`

Thanks
