### ISSUE TITLE
ASQG Format clarification

### ISSUE THREAD

**Issue by mariokostelac** [jts/sga#90]
I am working on [ASQG to AFG](https://github.com/mariokostelac/asqg2afg) file converter and it's not very clear what means when I have an overlap that looks like:

```
0 30 100 (start1, end1, len1)
0 20 200 (start2, end2, len2)
```
and second overlap is reversed.

Does it mean that overlap looks like
```
    ----->   (A)
<..... (*B)
```

where *B is actually a reversed complement of some read B from input set?

**Comment by jts** [comment]
Yes, your picture is correct.

To put it in string comparison terms, the coordinates indicate ```A[start1:end1] == rc(B[start2:end2])``` with inclusive end coordinates.

**Comment by mariokostelac** [comment]
Thank you @jts.
