### ISSUE TITLE
sga-preqc-report.py corrupted output file.

### ISSUE THREAD

**Issue by kumarsaurabh20** [jts/sga#97]
I am trying to get the genome size estimated using sga-preqc workflow. I have successfully generated .preqc file. But when I use sga-preqc-report.py script to generate a report, the resulting pdf file I get is always corrupted. It cannot be opened.
Do you have any idea how to get around this issue?

Many thanks for your time.

Best regards,
Kumar

**Comment by jts** [comment]
Hi Kumar,

Do you get any errors from the `sga preqc` or `sga-preqc-report.py` steps? Can you send me the .preqc file?

Jared

**Comment by jts** [comment]
Closed after discussion on email.
